name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt-get install shellcheck shfmt zsh

      - name: run shfmt
        run: find . -name '*.sh' -type f -print0 | xargs -0 -n1 -P4 shfmt -bn -ci -d -i 2 -ln bash -s -sr

      - name: run shellcheck
        run: find . -name '*.sh' -type f -print0 | xargs -0 -n1 -P4 shellcheck

      - name: "run zsh"
        run: find . -name '*.zsh' -type f -print0 | xargs -0 -n1 -P4 zsh -n

      - name: "run zcompile"
        run: find . -name '*.zsh' -type f -exec zsh -fc "zcompile {}" \;
